const { Discord, Client, Collection } = require('discord.js');
const bot = require("./bot.js")
const { intents, partials, ws } = require('./client.js');
const fs = require('fs');
const path = require("path")
const packageJson = require('../../package.json');
const client = new Client({ intents, partials, ws });
const { QuickDB } = require('quick.db');
const db = new QuickDB();
const mongose = require('./mongoDB.js')

module.exports = client;
client.token = bot.token;
client.cor = bot.cor;
client.prefix = bot.prefix;
client.mongoDB = mongose.chave;
client.author = packageJson.author;
client.commands = new Collection();
client.aliases = new Collection();
client.categories = fs.readdirSync(path.join(__dirname, '../commands'))